### ISSUE TITLE
Wrong timezone?

### ISSUE THREAD

**Issue by mishushakov** [digitalocean/DOKS#12]
Hey, my cronjob on managed kubernetes doesn't run as scheduled.
I'm within the same timezone as my cluster:

<img width="179" alt="Screenshot 2019-08-01 at 12 51 04" src="https://user-images.githubusercontent.com/10400064/62289104-2740e280-b45e-11e9-8d68-56352a27e619.png">

<img width="594" alt="Screenshot 2019-08-01 at 12 09 00" src="https://user-images.githubusercontent.com/10400064/62289115-2c059680-b45e-11e9-83f0-19104da492cf.png">

Is it a Kubernetes bug? Or what can i do to get it scheduled *on time*?
Thanks.

**Comment by mishushakov** [comment]
So, here my cronjob triggered 2 hrs later:

<img width="801" alt="Screenshot 2019-08-01 at 14 30 04" src="https://user-images.githubusercontent.com/10400064/62293440-ea2e1d80-b468-11e9-9718-9a77d43f2b44.png">

The time is UTC, right?

**Comment by timoreimann** [comment]
Yes, the time is UTC.

It looks correct to me: this is what I get when I `kubectl get` your `dialogflow-gateway-reporter` cronjob right now:

```
NAME                          SCHEDULE     SUSPEND   ACTIVE   LAST SCHEDULE   AGE
dialogflow-gateway-reporter   0 12 1 * *   False     0        7h36m           9h
```

And this is the time I end up with if I subtract those 7h36m from now:

```
$ date -u -d "- 7 hours - 36 mins"
Thu Aug  1 12:00:42 UTC 2019
```

I'm guessing your local machine isn't configured to UTC but CET?

**Comment by mishushakov** [comment]
Hey @timoreimann ✌️
I feel completely stupid now...

So, this is the time setting on my computer:

<img width="780" alt="Screenshot 2019-08-02 at 12 16 47" src="https://user-images.githubusercontent.com/10400064/62382459-e3c5a180-b54d-11e9-9b10-215aac7a07d4.png">

This is the output of `date` and `date -u` command on my local machine and alpine pod:

<img width="682" alt="Screenshot 2019-08-02 at 18 10 07" src="https://user-images.githubusercontent.com/10400064/62383746-d1009c00-b550-11e9-9129-d33db11a5cb9.png">

the time on my wrist is 18:xx

Does that mean, that in order to run 12:00 in my Berlin time i need to specify 10:00 in my cronjob? 
Or is it just `kubectl` displaying wrong time calculation and the job was actually executed as scheduled?

Thanks.

**Comment by timoreimann** [comment]
>Does that mean, that in order to run 12:00 in my Berlin time i need to specify 10:00 in my cronjob?

That's correct: as the clusters run on UTC, you will need to subtract 2 hours from your local Berlin / CEST time when considering what time you need to pass to kubectl.

>Or is it just kubectl displaying wrong time calculation and the job was actually executed as scheduled?

I couldn't spot a wrongly displayed calculation by kubectl. As long as you keep thinking in UTC, things should be correct.

**Comment by mishushakov** [comment]
👍
