### ISSUE TITLE
Automatic minor version k8s upgrades

### ISSUE THREAD

**Issue by ianmuscat** [digitalocean/DOKS#14]
Currently there seems to be no way to upgrade a Kubernetes cluster from one minor version to another. Therefore, upgrading to a new minor version of Kubernetes (e.g. from 1.14.x to 1.15.x) involves downtime in many cases since resources such as load balancers and persistent volumes need to either be re-created/re-attached manually.

**Comment by timoreimann** [comment]
@ianmuscat thanks for filing this feature request.

The possibility to carry out minor version upgrades automatically in a similar fashion to what we support today with regards to patch version upgrades is something we are actively working on right now. We're still fairly early in the process so unfortunately we cannot share a more specific timeline as of now. We'll be posting updates to this issue though as we make progress and hit important milestones.

**Comment by MichaelOrtho** [comment]
+1 👍

**Comment by timoreimann** [comment]
Quick update: we've making very solid progress on this feature. If things go as planned, we'll be able to provide support for minor version upgrades within a reasonable time frame.

Stay tuned.

**Comment by timoreimann** [comment]
As of today, automatic minor version upgrades are officially support. Please see [the blog post published earlier](https://blog.digitalocean.com/new-on-digitalocean-kubernetes/).
