### ISSUE TITLE
Support pod security policies

### ISSUE THREAD

**Issue by alexellis** [digitalocean/DOKS#17]
Are pod security policies supported yet?

I can't find a way to enable this in the user interface at digitalocean.com. 

Thanks

**Comment by timoreimann** [comment]
Hi Alex,

this is not supported at the moment, unfortunately. I'm happy to keep the ticket open to track progress on the necessary steps (notably a way to enable pod security policies on new / existing clusters and documentation / clusterlint checks to ensure users have set up proper policies beforehand).

**Comment by timoreimann** [comment]
PSPs have been deprecated upstream: https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

I'm closing this ticket. Once a replacement has been evolving far enough upstream, we can consider supporting that (which may possibly happen automatically once the potential feature reaches beta stage).
