### ISSUE TITLE
No metrics for cluster in version 1.20.2-do.0

### ISSUE THREAD

**Issue by chevdor** [digitalocean/DOKS#24]
Hello,

I am fighting to deploy the metrics-server and see CPU/Mem usage in the dashboard using a control plane with 1.20.2-do.0.

`kubectl top pods` returns:
```
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)
```

I have tried many things and current everything **appears* * to be running properly on the cluster, but still no metrics.

**Comment by timoreimann** [comment]
@chevdor if this is a vanilla installation of metrics-server, then you probably need to set `--kubelet-preferred-address-types=InternalIP`. (See also #2 and especially https://github.com/digitalocean/DOKS/issues/2#issuecomment-530822912.)

One easy way to ensure the metrics-server is working correctly on DOKS is to [install it from the DO Marketplace](https://marketplace.digitalocean.com/apps/kubernetes-metrics-server). I just verified that it works correctly on DOKS 1.20.

**Comment by chevdor** [comment]
This is what I initially did and the dashboard works indeed, but not the
charts/metrics.

**Comment by timoreimann** [comment]
@chevdor by charts/metrics, you mean Helm charts?

Can you share any manifests describing your configuration?

**Comment by chevdor** [comment]
No I mean the metrics charts in the dashboard, showing cpu and men usage
over time, for nodes and pods.

Although, after chatting with DO support, I have been told that it cannot
(unfortunately) work because DO does not deploy the scrapper on the DO
dashboard. This is also a dashboard users cannot modify.

So the only workaround atm is for users to install the dashboard again,
giving them a second version they can customize.

>

**Comment by timoreimann** [comment]
That's (unfortunately) correct for the time being. You can follow #21 to be notified when we support metrics in the dashboard.

**Comment by timoreimann** [comment]
Let's close this ticket to keep any dashboard-specific discussions around metrics focused in one issue.
