### ISSUE TITLE
Linux Kernel 5.x on DOKS Nodes

### ISSUE THREAD

**Issue by artem-zinnatullin** [digitalocean/DOKS#29]
We intend to deploy an application that uses [`io_uring` API](https://en.wikipedia.org/wiki/Io_uring) of Linux Kernel on DigitalOcean Kubernetes Service .

The API was added to the Linux Kernel 5.1, released on May 5th 2019.

But it turns out DOKS Nodes [are running on Linux 4.19.0-17](https://docs.digitalocean.com/products/kubernetes/changelog/#1212-do0-2021-06-29) thus making `io_uring` unavailable for k8s containers.

Is there a planned date on upgrading DOKS nodes to Linux Kernel 5.x?  Thanks

**Comment by timoreimann** [comment]
Hey @artem-zinnatullin 👋 

Upgrading the kernel to 5.x is in the making. I can't speak to specific timelines, but it shouldn't take terribly long anymore until a newer kernel version becomes available.

Stay tuned!

**Comment by artem-zinnatullin** [comment]
Oh that's good to hear, I love the service and would like to use DigitalOcean for the project, but `io_uring` is a blocker for us, hopefully our release timeline matches yours and we'll be able to deploy on DOKS 😬

**Comment by bergkvist** [comment]
Any updates on this? I want to use the "Egress Gateway" feature in Cilium, which requires kernel version >= 5.2 https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/

**Comment by timoreimann** [comment]
We just realized DOKS 1.22 which comes with kernel 5.10. See also [our release notes](https://docs.digitalocean.com/products/kubernetes/changelog/).

@bergkvist please be aware that we consider the Cilium configuration to be part of the managed offering, so changes you may do to it can be overwritten by our backend systems.

Additionally, the egress gateway feature in Cilium was still somewhat buggy when we tested it in 1.10. I think a few improvements went into Cilium 1.11, but we do not support that yet in DOKS.
