### ISSUE TITLE
Support auto-scaling DOKS clusters

### ISSUE THREAD

**Issue by timoreimann** [digitalocean/DOKS#5]
Being able to auto-scale DOKS clusters/nodes seems beneficial to address users with rather dynamic work loads.

We should probably look into https://github.com/kubernetes/autoscaler for this purpose.

**Comment by timoreimann** [comment]
kubernetes/autoscaler#254 was recently reopened to track adding auto-scaling support for DOKS. @fatih is going to work on it.

**Comment by timoreimann** [comment]
The upstream effort to kubernetes/autoscaler has been merged. 🎉(Kudos, @fatih 👏 )

The next step is to integrate the work into the DOKS product. We yet need to flesh out the details on how that'd look like. Keep following this issue for updates as we move forward.

**Comment by manelpb** [comment]
Any update about this?

**Comment by timoreimann** [comment]
Things are looking pretty good at this stage. There's a fair chance the next round of DOKS images is going to come with autoscaling support for certain Kubernetes releases.

**Comment by pablokbs** [comment]
Seems like DO announced autoscaling today?

https://blog.digitalocean.com/new-on-digitalocean-kubernetes/

**Comment by timoreimann** [comment]
@pablokbs that's right, autoscaling shipped today. 🌠 Thanks for sharing the link.

I think we're good to close this one. Any future extensions to the autoscaling support in DOKS should be filed as a new issue.
